version: 2.1
jobs:
  build-deploy-test:
    steps:
      - checkout
      - setup_remote_docker
      - run: |
        docker run --cap-add IPC_LOCK -e "VAULT_ADDR=https://clotho.broadinstitute.org:8200" 
