apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: template-vservice
spec:
  hosts:
  - "*"
  gateways:
  - template-gateway.default.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8080
        host: template-deployment-service.dev.svc.cluster.local
