apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: kernel-service-poc-service-psp
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: false
  allowedCapabilities:
    - 'NET_ADMIN'
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
