  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: demo-service-clusterrole-binding
  roleRef:
    kind: ClusterRole
    name: demo-service-clusterrole
    apiGroup: rbac.authorization.k8s.io
  subjects:
  # Authorize specific service accounts:
  - kind: ServiceAccount
    name: demo-service-sa