name: Tag, Build, and Push Image

on:
  push:
    branches:
    - gm-dispatch
env:
  SERVICE_NAME: workspace-test
  GOOGLE_PROJECT: terra-kernel-k8s
  GKE_CLUSTER: terra-kernel-k8s
  VAULT_PATH_GCR: secret/dsde/terra/kernel/test
  VAULT_ADDR: https://clotho.broadinstitute.org:8200
jobs:
  tag-build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current code
      uses: actions/checkout@master
    - name: Bump version and push tag
      id: tag
      uses: broadinstitute/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_BRANCHES: gm-dispatch
        WITH_V: false
    - name: Repository Dispatch
        uses: broadinstitute/repository-dispatch@master
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: databiosphere/framework-version
          event-type: my-event
          client-payload: '{"service": "${{ env.SERVICE_NAME }}", "tag": "${{ steps.tag.outputs.tag }}"}'
