name: Dispatch Test

on:
  push:
    branches:
    - gm-dispatch
env:
  SERVICE_NAME: ${{ github.event.repository.name }}
jobs:
  tag-dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current code
      uses: actions/checkout@master
    - name: Bump version and push tag
      id: tag
      uses: broadinstitute/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_BRANCHES: gm-dispatch
        WITH_V: false
    - name: Repository Dispatch
      uses: broadinstitute/repository-dispatch@master
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: databiosphere/framework-version
        event-type: version-bump
        client-payload: '{"service": "${{ env.SERVICE_NAME }}", "tag": "${{ steps.tag.outputs.tag }}"}'
