name: Manage Preview Environment

on:
  issue_comment:
    types: [created]

jobs:
  preview-create:
    name: Create Preview Environment
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'preview create'
    steps:
    - name: Create
      id: create
      uses: broadinstitute/terra-preview/create@master

  preview-test:
    name: Run Tests in Preview Environment
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'preview test'
    steps:
    - name: Create
      id: create
      uses: broadinstitute/terra-preview/create@master
    - name: Test
      id: test
      uses: ./.github/actions/test
      with:
        endpoints: ${{ steps.create.outputs.endpoints }}
        versions: ${{ steps.create.outputs.versions }}
    - name: Report
      id: report
      uses: broadinstitute/terra-preview/report@master
      with:
        status: ${{ steps.test.outputs.status }}
        testData: ${{ steps.test.outputs.testData }}
        pullRequests: ${{ steps.test.outputs.pullRequests }}
    - name: Delete
      uses: broadinstitute/terra-preview/delete@master
      if: ${{ steps.test.outputs.status }} == 'true'

  preview-delete:
    name: Delete Preview Environment
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'preview delete'
    steps:
    - name: Delete
      uses: broadinstitute/terra-preview/delete@master
